schema
  @link(url: "https://specs.apollo.dev/link/v1.0")
  @link(url: "https://specs.apollo.dev/join/v0.5", for: EXECUTION)
{
  query: Query
}

directive @join__directive(graphs: [join__Graph!], name: String!, args: join__DirectiveArguments) repeatable on SCHEMA | OBJECT | INTERFACE | FIELD_DEFINITION

directive @join__enumValue(graph: join__Graph!) repeatable on ENUM_VALUE

directive @join__field(graph: join__Graph, requires: join__FieldSet, provides: join__FieldSet, type: String, external: Boolean, override: String, usedOverridden: Boolean, overrideLabel: String, contextArguments: [join__ContextArgument!]) repeatable on FIELD_DEFINITION | INPUT_FIELD_DEFINITION

directive @join__graph(name: String!, url: String!) on ENUM_VALUE

directive @join__implements(graph: join__Graph!, interface: String!) repeatable on OBJECT | INTERFACE

directive @join__type(graph: join__Graph!, key: join__FieldSet, extension: Boolean! = false, resolvable: Boolean! = true, isInterfaceObject: Boolean! = false) repeatable on OBJECT | INTERFACE | UNION | ENUM | INPUT_OBJECT | SCALAR

directive @join__unionMember(graph: join__Graph!, member: String!) repeatable on UNION

directive @link(url: String, as: String, for: link__Purpose, import: [link__Import]) repeatable on SCHEMA

interface Interface1
  @join__type(graph: A)
  @join__type(graph: B)
{
  id: ID!
  interface4: Interface4 @join__field(graph: A)
  type21s: [Type21!]! @join__field(graph: A)
  foo: String @join__field(graph: B)
}

interface Interface1A
  @join__type(graph: A)
  @join__type(graph: B)
{
  id: ID!
  interface4: Interface4 @join__field(graph: A)
  type21s: [Type21!]! @join__field(graph: A)
  foo: String @join__field(graph: B)
}

interface Interface2
  @join__type(graph: A)
  @join__type(graph: B)
{
  id: ID!
  foo: String @join__field(graph: A)
  bar: String @join__field(graph: B)
  interface4: Interface4 @join__field(graph: B)
}

interface Interface3
  @join__type(graph: A)
  @join__type(graph: B)
{
  id: ID!
  foo: String @join__field(graph: A)
  bar: String @join__field(graph: B)
}

interface Interface4
  @join__type(graph: A)
  @join__type(graph: B)
{
  id: ID!
  bar: String @join__field(graph: A)
  foo: String @join__field(graph: B)
  type6s: [Type6!]! @join__field(graph: B)
  interface5: Interface5 @join__field(graph: B)
}

interface Interface5
  @join__type(graph: A)
  @join__type(graph: B)
{
  foo: String
}

input join__ContextArgument {
  name: String!
  type: String!
  context: String!
  selection: join__FieldValue!
}

scalar join__DirectiveArguments

scalar join__FieldSet

scalar join__FieldValue

enum join__Graph {
  A @join__graph(name: "a", url: "http://localhost:8070/query")
  B @join__graph(name: "b", url: "http://localhost:8071/query")
}

scalar link__Import

enum link__Purpose {
  """
  `SECURITY` features provide metadata necessary to securely resolve fields.
  """
  SECURITY

  """
  `EXECUTION` features provide metadata necessary for operation execution.
  """
  EXECUTION
}

type Query
  @join__type(graph: A)
  @join__type(graph: B)
{
  interface1ById(id: ID!): Interface1 @join__field(graph: B)
}

type Type11 implements Interface1 & Interface1A
  @join__implements(graph: A, interface: "Interface1")
  @join__implements(graph: A, interface: "Interface1A")
  @join__implements(graph: B, interface: "Interface1")
  @join__implements(graph: B, interface: "Interface1A")
  @join__type(graph: A, key: "id")
  @join__type(graph: B, key: "id")
{
  id: ID!
  interface4: Interface4 @join__field(graph: A)
  type21s: [Type21!]! @join__field(graph: A)
  foo: String @join__field(graph: B)
}

type Type12 implements Interface1 & Interface1A
  @join__implements(graph: A, interface: "Interface1")
  @join__implements(graph: A, interface: "Interface1A")
  @join__type(graph: A)
{
  id: ID!
  interface4: Interface4
  foo: String
  type21s: [Type21!]!
}

type Type13 implements Interface1 & Interface1A
  @join__implements(graph: A, interface: "Interface1")
  @join__implements(graph: A, interface: "Interface1A")
  @join__implements(graph: B, interface: "Interface1")
  @join__implements(graph: B, interface: "Interface1A")
  @join__type(graph: A, key: "id")
  @join__type(graph: B, key: "id")
{
  id: ID!
  interface4: Interface4 @join__field(graph: A)
  type21s: [Type21!]! @join__field(graph: A)
  foo: String @join__field(graph: B)
}

type Type14 implements Interface1
  @join__implements(graph: A, interface: "Interface1")
  @join__implements(graph: B, interface: "Interface1")
  @join__type(graph: A, key: "id")
  @join__type(graph: B, key: "id")
{
  id: ID!
  interface4: Interface4 @join__field(graph: A)
  type21s: [Type21!]! @join__field(graph: A)
  foo: String @join__field(graph: B)
}

type Type15 implements Interface1
  @join__implements(graph: A, interface: "Interface1")
  @join__implements(graph: B, interface: "Interface1")
  @join__type(graph: A, key: "id")
  @join__type(graph: B, key: "id")
{
  id: ID!
  interface4: Interface4 @join__field(graph: A)
  type21s: [Type21!]! @join__field(graph: A)
  foo: String @join__field(graph: B)
}

type Type16 implements Interface1
  @join__implements(graph: A, interface: "Interface1")
  @join__implements(graph: B, interface: "Interface1")
  @join__type(graph: A, key: "id")
  @join__type(graph: B, key: "id")
{
  id: ID!
  interface4: Interface4 @join__field(graph: A)
  type21s: [Type21!]! @join__field(graph: A)
  foo: String @join__field(graph: B)
}

type Type21 implements Interface2
  @join__implements(graph: A, interface: "Interface2")
  @join__implements(graph: B, interface: "Interface2")
  @join__type(graph: A, key: "id")
  @join__type(graph: B, key: "id")
{
  id: ID!
  foo: String @join__field(graph: A)
  bar: String @join__field(graph: B)
  interface4: Interface4 @join__field(graph: B)
}

type Type22 implements Interface2
  @join__implements(graph: A, interface: "Interface2")
  @join__implements(graph: B, interface: "Interface2")
  @join__type(graph: A, key: "id")
  @join__type(graph: B, key: "id")
{
  id: ID!
  foo: String @join__field(graph: A)
  bar: String @join__field(graph: B)
  interface4: Interface4 @join__field(graph: B)
}

type Type31 implements Interface3
  @join__implements(graph: A, interface: "Interface3")
  @join__implements(graph: B, interface: "Interface3")
  @join__type(graph: A, key: "id")
  @join__type(graph: B, key: "id")
{
  id: ID!
  foo: String @join__field(graph: A)
  bar: String @join__field(graph: B)
}

type Type32 implements Interface3
  @join__implements(graph: A, interface: "Interface3")
  @join__implements(graph: B, interface: "Interface3")
  @join__type(graph: A, key: "id")
  @join__type(graph: B, key: "id")
{
  id: ID!
  foo: String @join__field(graph: A)
  bar: String @join__field(graph: B)
}

type Type33 implements Interface3
  @join__implements(graph: A, interface: "Interface3")
  @join__implements(graph: B, interface: "Interface3")
  @join__type(graph: A, key: "id")
  @join__type(graph: B, key: "id")
{
  id: ID!
  foo: String @join__field(graph: A)
  bar: String @join__field(graph: B)
}

type Type41 implements Interface4
  @join__implements(graph: A, interface: "Interface4")
  @join__implements(graph: B, interface: "Interface4")
  @join__type(graph: A, key: "id")
  @join__type(graph: B, key: "id")
{
  id: ID!
  bar: String @join__field(graph: A)
  foo: String @join__field(graph: B)
  type6s: [Type6!]! @join__field(graph: B)
  interface5: Interface5 @join__field(graph: B)
}

type Type42 implements Interface4
  @join__implements(graph: A, interface: "Interface4")
  @join__implements(graph: B, interface: "Interface4")
  @join__type(graph: A, key: "id")
  @join__type(graph: B, key: "id")
{
  id: ID!
  foo: String
  bar: String @join__field(graph: A)
  type6s: [Type6!]!
  interface5: Interface5
}

type Type51 implements Interface5
  @join__implements(graph: A, interface: "Interface5")
  @join__implements(graph: B, interface: "Interface5")
  @join__type(graph: A)
  @join__type(graph: B)
{
  foo: String
  bar1: String
}

type Type52 implements Interface5
  @join__implements(graph: A, interface: "Interface5")
  @join__implements(graph: B, interface: "Interface5")
  @join__type(graph: A)
  @join__type(graph: B)
{
  foo: String
  bar2: String
}

type Type53 implements Interface5
  @join__implements(graph: A, interface: "Interface5")
  @join__implements(graph: B, interface: "Interface5")
  @join__type(graph: A)
  @join__type(graph: B)
{
  foo: String
  bar3: String
}

type Type54 implements Interface5
  @join__implements(graph: A, interface: "Interface5")
  @join__implements(graph: B, interface: "Interface5")
  @join__type(graph: A)
  @join__type(graph: B)
{
  foo: String
  bar4: String
}

type Type55 implements Interface5
  @join__implements(graph: A, interface: "Interface5")
  @join__implements(graph: B, interface: "Interface5")
  @join__type(graph: A)
  @join__type(graph: B)
{
  foo: String
  bar5: String
}

type Type6
  @join__type(graph: A)
  @join__type(graph: B)
{
  interface3: Interface3
}
