package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"
	"main/graph/model"
)

// FindCommentModerationInfoByID is the resolver for the findCommentModerationInfoByID field.
func (r *entityResolver) FindCommentModerationInfoByID(ctx context.Context, id string) (*model.CommentModerationInfo, error) {
	panic(fmt.Errorf("not implemented: FindCommentModerationInfoByID - findCommentModerationInfoByID"))
}

// FindPostModerationInfoByID is the resolver for the findPostModerationInfoByID field.
func (r *entityResolver) FindPostModerationInfoByID(ctx context.Context, id string) (*model.PostModerationInfo, error) {
	panic(fmt.Errorf("not implemented: FindPostModerationInfoByID - findPostModerationInfoByID"))
}

// FindSubredditPostByID is the resolver for the findSubredditPostByID field.
func (r *entityResolver) FindSubredditPostByID(ctx context.Context, id string) (*model.SubredditPost, error) {
	panic(fmt.Errorf("not implemented: FindSubredditPostByID - findSubredditPostByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
