// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ModerationInfo interface {
	IsModerationInfo()
	GetID() string
	GetBar() *string
}

type Post interface {
	IsPost()
	GetID() string
}

type PostInfo interface {
	IsPostInfo()
	GetID() string
}

type CommentModerationInfo struct {
	ID  string  `json:"id"`
	Bar *string `json:"bar,omitempty"`
}

func (CommentModerationInfo) IsEntity() {}

type PostModerationInfo struct {
	ID  string  `json:"id"`
	Foo *string `json:"foo,omitempty"`
	Bar *string `json:"bar,omitempty"`
}

func (PostModerationInfo) IsEntity() {}

type Query struct {
}

type SubredditPost struct {
	ID             string         `json:"id"`
	ModerationInfo ModerationInfo `json:"moderationInfo,omitempty"`
}

func (SubredditPost) IsPostInfo()        {}
func (this SubredditPost) GetID() string { return this.ID }

func (SubredditPost) IsPost() {}

func (SubredditPost) IsEntity() {}
