package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.76

import (
	"context"
	"fmt"
	"main/graph/model"
)

// FindCommentModerationInfoByID is the resolver for the findCommentModerationInfoByID field.
func (r *entityResolver) FindCommentModerationInfoByID(ctx context.Context, id string) (*model.CommentModerationInfo, error) {
	panic(fmt.Errorf("not implemented: FindCommentModerationInfoByID - findCommentModerationInfoByID"))
}

// FindPostModerationInfoByID is the resolver for the findPostModerationInfoByID field.
func (r *entityResolver) FindPostModerationInfoByID(ctx context.Context, id string) (*model.PostModerationInfo, error) {
	panic(fmt.Errorf("not implemented: FindPostModerationInfoByID - findPostModerationInfoByID"))
}

// FindSubredditPostByID is the resolver for the findSubredditPostByID field.
func (r *entityResolver) FindSubredditPostByID(ctx context.Context, id string) (*model.SubredditPost, error) {
	panic(fmt.Errorf("not implemented: FindSubredditPostByID - findSubredditPostByID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *entityResolver) FindSimplePostByID(ctx context.Context, id string) (*model.SimplePost, error) {
	panic(fmt.Errorf("not implemented: FindSimplePostByID - findSimplePostByID"))
}
*/
