# B

extend schema @link(url: "https://specs.apollo.dev/federation/v2.9", import: ["@key", "@shareable"])

type Query {
  interface1ById(id: ID!): Interface1
}

interface Interface1 {
  id: ID!
  foo: String
}

interface Interface1A {
  id: ID!
  foo: String
}

type Type11 implements Interface1 & Interface1A @key(fields: "id") {
  id: ID!
  foo: String
}

type Type13 implements Interface1 & Interface1A @key(fields: "id") {
  id: ID!
  foo: String
}

type Type14 implements Interface1 @key(fields: "id") {
  id: ID!
  foo: String
}

type Type15 implements Interface1 @key(fields: "id") {
  id: ID!
  foo: String
}

type Type16 implements Interface1 @key(fields: "id") {
  id: ID!
  foo: String
}

interface Interface4 {
  id: ID!
  foo: String
  type6s: [Type6!]!
  interface5: Interface5
}

type Type41 implements Interface4 @key(fields: "id") {
  id: ID!
  foo: String
  type6s: [Type6!]!
  interface5: Interface5
}

type Type42 implements Interface4 @shareable {
  id: ID!
  foo: String
  bar: String
  type6s: [Type6!]!
  interface5: Interface5
}

interface Interface3 {
  id: ID!
  bar: String
}

type Type31 implements Interface3 @key(fields: "id") {
  id: ID!
  bar: String
}

type Type32 implements Interface3 @key(fields: "id") {
  id: ID!
  bar: String
}

type Type33 implements Interface3 @key(fields: "id") {
  id: ID!
  bar: String
}

interface Interface2 {
  id: ID!
  bar: String
  interface4: Interface4
}

type Type21 implements Interface2 @key(fields: "id") {
  id: ID!
  bar: String
  interface4: Interface4
}

type Type22 implements Interface2 @key(fields: "id") {
  id: ID!
  bar: String
  interface4: Interface4
}

type Type6 @shareable {
  interface3: Interface3
}

interface Interface5 {
  foo: String
}

type Type51 implements Interface5 @shareable {
  foo: String
  bar1: String
}

type Type52 implements Interface5 @shareable {
  foo: String
  bar2: String
}

type Type53 implements Interface5 @shareable {
  foo: String
  bar3: String
}

type Type54 implements Interface5 @shareable {
  foo: String
  bar4: String
}

type Type55 implements Interface5 @shareable {
  foo: String
  bar5: String
}